travis:
  secure:
    BINSTAR_TOKEN: qnC3N5p4HURj415fyPFfDHdRA/rdX/+6ZxX5vU+ECQWL6BK4UTbp/RvFuPmr4zCoQV1ZN/qTpN0u4r0a8vceM3acjgEKSgDWpDaD7jN/xXFWVuE2/p3xKDWb3ZbZnO8X/NNCXZt9ssrTs67zkxui3+BEQh5/Nc5cnpXpdaCKCXPDJZrJTdzl8Uy+OH4KkUSCgtmqcHRg/TAdbK7Yo5rjUxx2TNLVLd1l1M0DYidfwNk5sVIruBji5wRsmAc+u3ck5XNDnvjFOt8jK5tft9liVtb5qrVqmv+tBtwjMpC7G3dkkXa7mU1esFVbjc6uP3OTfk2wUllidC3LzyFwDDxCzgnn2qUAj9qQQ8MVz0mWB0AUC/4I7iRSZF1aEy80LaXJ/5SIXFhiwNGNScC+9rb2wIe5OyoCXMdLcHCS7U0uq2QLPCi27529lQ697b2kmHFTEL5OyOH+Zoq1Qp/QRYa47FB/ml2S5vd0xOcRrbFAx9PR+Db6JUlnqx85bhvW5FNQ3NpCi9WmZtglVxvGX1KXihV2jsymu8NMHldUTwUHiFkIUdKhWqPeUDyOAtrk7U0TmuxBBp4/APx9TpJP6A4BecIt51ANfkIJvzpzYRPL6Vehz4INqmKUluq7QAUwcOm0BCPOMT1gkVfnzmDoRQMkDCBtGXur3gj7UQHZsqTIG2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
